docs: add multiple examples
lacework/terraform-azure-activity-log pull request #78
Opened 2023-03-16 01:46 UTC by afiune

## Summary

We are adding a few examples to clarify how to onboard multiple scenarios:
* single tenant single subscription
* single tenant multiple subscriptions
* single tenant all subscriptions
* multiple tenants all subscriptions

## How did you test this change?

Added these examples to run in our CI pipeline.

## Issue
https://lacework.atlassian.net/browse/GROW-1446

2023-03-16 16:07 UTC, jon-stewart approved these changes
Do we need an example for subscription_id in the azurerm block (GROW-1444)?

2023-03-17 18:06 UTC, sthetland requested changes
Looks good basically.. some minor comments/suggestions.

2023-03-17 18:06 UTC, sthetland commented on examples/default-activity-log/README.md
> +For detailed information on integrating Lacework with Azure see [Azure Compliance & Activity Log Integrations - Terraform From Any Supported Host](https://docs.lacework.com/onboarding/azure-complianc
```suggestion
For detailed information on integrating Lacework with Azure, see [Azure Compliance & Activity Log Integrations - Terraform From Any Supported Host](https://docs.lacework.com/onboarding/azure-compliance-and-activity-log-integrations-terraform-from-any-supported-host).
```

2023-03-17 18:06 UTC, sthetland commented on examples/existing-storage-account/README.md
> +For detailed information on integrating Lacework with Azure see [Azure Compliance & Activity Log Integrations - Terraform From Any Supported Host](https://docs.lacework.com/onboarding/azure-complianc
```suggestion
For detailed information on integrating Lacework with Azure, see [Azure Compliance & Activity Log Integrations - Terraform From Any Supported Host](https://docs.lacework.com/onboarding/azure-compliance-and-activity-log-integrations-terraform-from-any-supported-host).
```

2023-03-17 18:06 UTC, sthetland commented on examples/multiple-subscriptions-in-tenant/README.md
> +single Azure tenant.
as above..

```suggestion
single Azure tenant with Lacework for Activity Log analysis.
```

2023-03-17 18:06 UTC, sthetland commented on examples/multiple-subscriptions-in-tenant/README.md
> +For detailed information on integrating Lacework with Azure see [Azure Compliance & Activity Log Integrations - Terraform From Any Supported Host](https://docs.lacework.com/onboarding/azure-complianc
```suggestion
For detailed information on integrating Lacework with Azure, see [Azure Compliance & Activity Log Integrations - Terraform From Any Supported Host](https://docs.lacework.com/onboarding/azure-compliance-and-activity-log-integrations-terraform-from-any-supported-host).
```

2023-03-17 18:06 UTC, sthetland commented on examples/multiple-tenants/README.md
> +The following example integrates multiple Azure tenants and all their subscriptions
```suggestion
The following example integrates multiple Azure tenants and all their subscriptions with Lacework for Activity Log analysis.
```

2023-03-17 18:06 UTC, sthetland commented on examples/multiple-tenants/README.md
> +For detailed information on integrating Lacework with Azure see [Azure Compliance & Activity Log Integrations - Terraform From Any Supported Host](https://docs.lacework.com/onboarding/azure-complianc
```suggestion
For detailed information on integrating Lacework with Azure. see [Azure Compliance & Activity Log Integrations - Terraform From Any Supported Host](https://docs.lacework.com/onboarding/azure-compliance-and-activity-log-integrations-terraform-from-any-supported-host).
```

2023-03-20 17:41 UTC, sthetland approved these changes
LGTM

2023-03-20 21:36 UTC, merged